/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproyecto1.views;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import miniproyecto1.controllers.Controller;
import miniproyecto1.dbConnections.MySQLdbConnection;
import miniproyecto1.models.Aula;
import miniproyecto1.models.Aula_curso;
import miniproyecto1.models.Curso_horario;
import miniproyecto1.models.Horario;
import miniproyecto1.models.Inscripcion;

/**
 *
 * @author Jessele Durán
 */
public class InscripcionRegisterView extends javax.swing.JFrame {

    /**
     * Creates new form InscripcionRegisterView
     */
    public InscripcionRegisterView(MySQLdbConnection db, LinkedHashMap<String, Object> adm) throws Exception {
        super("Registrar Inscripción");
        this.db = db;
        this.adm = adm;
        
        initComponents();
        fillTableCliente();
        fillTableCurso();
        initJList();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        participanteTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cursoTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        aulaList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        horarioList = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Registrar Inscripción");

        participanteTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        participanteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        participanteTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                participanteTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(participanteTable);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Escoger Participante:");

        cursoTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cursoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        cursoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursoTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cursoTable);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Escoger Curso:");

        aceptarButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        aceptarButton.setText("Registrar");
        aceptarButton.setToolTipText("");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Horario:");

        aulaList.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        aulaList.setModel(modelList);
        jScrollPane3.setViewportView(aulaList);

        horarioList.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        horarioList.setModel(horarioModelList);
        jScrollPane4.setViewportView(horarioList);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Aula:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void participanteTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_participanteTableMouseClicked
        if (evt.getClickCount() == 1)
        {
            int fila =participanteTable.getSelectedRow();
            ci_participante = (long) participanteTable.getValueAt(fila,1);
            System.out.println(ci_participante);

        }
    }//GEN-LAST:event_participanteTableMouseClicked

    private void cursoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursoTableMouseClicked
        if (evt.getClickCount() == 1)
        {

            int fila =cursoTable.getSelectedRow();
            id_curso= (Integer) cursoTable.getValueAt(fila,0);
            System.out.println(id_curso);

        }
    }//GEN-LAST:event_cursoTableMouseClicked

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        List aulas = aulaList.getSelectedValuesList();
        List horarios = horarioList.getSelectedValuesList();
        try
        {
            if(validaciones() != true)
            {
                LinkedHashMap<String, Object> map = new LinkedHashMap<String,Object>();

                map.put("ci_cliente", ci_participante);
                map.put("ci_admin", adm.get("3"));
                map.put("id_curso", id_curso);

                Controller<Inscripcion> controller = new Controller<Inscripcion>(Inscripcion.class);

                if(controller.insert(map, db) == true)
                {
                    Controller<Aula_curso> controllerAula_curso = new Controller<Aula_curso>(Aula_curso.class); 
                    Controller<Curso_horario> controllerCurso_horario = new Controller<Curso_horario>(Curso_horario.class);
                    for (int i=0;i < aulas.size();i++)
                    {
                        LinkedHashMap<String, Object> mapAula_curso = new LinkedHashMap<String,Object>();
                        
                        mapAula_curso.put("id_aula", aulas.get(i));
                        mapAula_curso.put("id_curso", id_curso);
                        System.out.println(mapAula_curso);
                        controllerAula_curso.insert(mapAula_curso, db);
                    }
                    
                    for (int i=0;i < horarios.size();i++)
                    {
                        LinkedHashMap<String, Object> mapCurso_horario = new LinkedHashMap<String,Object>();
                        
                        mapCurso_horario.put("id_curso", id_curso);
                        mapCurso_horario.put("id_horario", (controller.findHorario(horarios.get(i).toString(), db)));
                 
                        System.out.println(mapCurso_horario);
                        controllerCurso_horario.insert(mapCurso_horario, db);
                    }
    
                    dispose();
                    JOptionPane.showMessageDialog(null, "La Incripción se ha registrado correctamente", "Registro con éxito", JOptionPane.INFORMATION_MESSAGE);
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Error al inscribir Participante","ERROR",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch(Exception e)
        {

            JOptionPane.showMessageDialog(null,"Error: "+e.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        dispose() ;
    }//GEN-LAST:event_cancelarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JList<String> aulaList;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTable cursoTable;
    private javax.swing.JList<String> horarioList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable participanteTable;
    // End of variables declaration//GEN-END:variables
    private MySQLdbConnection db;
    DefaultListModel modelList = new DefaultListModel();
    DefaultListModel horarioModelList = new DefaultListModel();
    
    private Integer id_curso;
    private long ci_participante;
    LinkedHashMap<String, Object> adm;
    
    public void fillTableCliente() throws Exception
    {
        String sql = "SELECT * FROM cliente";
        db.open();
        ResultSet resultSet = db.getResultSet(sql);
        participanteTable.setModel(buildTableModel(resultSet));
        db.close();
    }
    
    public void fillTableCurso() throws Exception
    {
        String sql = "SELECT * FROM curso";
        db.open();
        ResultSet resultSet = db.getResultSet(sql);
        cursoTable.setModel(buildTableModel(resultSet));
        db.close();
    }
 
    
    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException 
    {
        ResultSetMetaData metaData = rs.getMetaData();
        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) 
        {
            columnNames.add(metaData.getColumnName(column));
        }
        System.out.println(columnNames);

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) 
        {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) 
            {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        System.out.println(data);

 
        return new DefaultTableModel(data, columnNames) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
    }
    
    public boolean validaciones()
    {
        if(id_curso == 0)
        {
                JOptionPane.showMessageDialog(null,"Error:Debe escoger un curso","ERROR",JOptionPane.ERROR_MESSAGE);
                return true;
        }
        
        if(ci_participante == 0)
        {
                JOptionPane.showMessageDialog(null,"Error: Debe escoger un cliente","ERROR",JOptionPane.ERROR_MESSAGE);
                return true;
        }         
        
        return false;
    }
    
    public void initJList() throws Exception
    {
        cursoTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        participanteTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        aulaList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        horarioList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        Controller<Aula> aula = new Controller<Aula>(Aula.class);
        List<LinkedHashMap<String, Object>> list = aula.getAll(db); //lista de resultados
        ArrayList array = new ArrayList();
        for (Iterator<LinkedHashMap<String, Object>> i = list.iterator(); i.hasNext();) 
        {
            LinkedHashMap<String, Object> item = i.next();
            String valor = (String) item.get("id");
            System.out.println("aula:"+valor);
            modelList.addElement(valor);
        }
        
        
        Controller<Horario> horario = new Controller<Horario>(Horario.class);
        List<LinkedHashMap<String, Object>> listHorario = horario.getAll(db); //lista de resultados
        ArrayList arrayHorario = new ArrayList();
        for (Iterator<LinkedHashMap<String, Object>> i = listHorario.iterator(); i.hasNext();) 
        {
            LinkedHashMap<String, Object> itemHorario = i.next();
            String valorInicial = (String) itemHorario.get("hr_inicio");
            String valorFinal = (String) itemHorario.get("hr_final");
            String valorCombo = (String) (valorInicial+" - "+valorFinal);
            System.out.println("combo:"+valorCombo);
            horarioModelList.addElement(valorCombo);
        }   
    }
}
